# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java 8 CI with Maven

on:
  push:
    branches: [ develop, 3.1.x, 3.0.x ]
  pull_request:
    branches: [ develop, 3.1.x, 3.0.x ]
  schedule:
    - cron: 0 5 * * 1


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        # Step that does that actual cache save and restore
    - name: Cache 
      uses: actions/cache@v1
      with:
       path: ~/.m2/repository
       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       restore-keys: |
        ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package --file pom.xml
